# This is a basic workflow to help you get started with Actions

name: Test on BSC

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-on-bsc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DEPAY_MNEMONIC: ${{secrets.DEPAY_MNEMONIC}}
      BSC_RPC_URL: ${{secrets.BSC_RPC_URL}}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a single command using the runners shell
      - name: Install packages
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: Create .env file
        run: |
          echo "NODE_ENV=development" >> .env,
          echo "MNEMONIC=${DEPAY_MNEMONIC}" >> .env,
          echo "BSC_RPC_URL=${BSC_RPC_URL}" >> .env

      - name: Compile
        run: yarn compile

      - name: Run test
        run: yarn test:bsc
